version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tomrootcofeetom
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuserpassforus

  wordpress:
    image: wordpress:5.1.1
    container_name: wordpress
    restart: always
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - "52:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuserpassforus
    depends_on:
       - db
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '80:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: tomrootcofeetom
    depends_on:
      - db


volumes:
    db_data:
